# frozen_string_literal: true
source "https://rubygems.org"

gem "sinatra-activerecord"
gem "sqlite3"
gem "pry"
gem "require_all"
gem "faker"
gem "rake"
gem "rspec"
#gem "rspec-rails"
#gem "rails"
gem "database_cleaner"
gem "google-cloud-translate"
gem "colorize"
gem "artii"